### ISSUE TITLE
Decople release pipeline

### ISSUE THREAD

**Issue by Noly** [newrelic/fluent-bit-package#21]
Now `.zip` assets are generated in same action flow. 
Since windows release process is different from Linux (windows is embedded in the infra-agent vs linux assets are included as dependencies) could be some cases where We will be interested to only release a new version for windows or linux.

## Possible Solution

Split the workflow and create a manual staged,
```
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to pre-release'
        required: true
      assetsType:
        description: 'Assets type to pre-release: all, zip, deb, rpm'
        required: true
        default: 'all'
```

And in job using [jobs.<job_id>.if](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idif)

## Additional context

Reference: [infra-agent](https://github.com/newrelic/infrastructure-agent/blob/master/.github/workflows/prerelease_staged_publish.yml)
